#all:HCAbft 
#.PHONY:all
#SIMGRID_INSTALL_PATH = /home/Research/SimGrid-3.12
#CC = smpicc
#
#CFLAGES = -std=gnu99 
#
##HCAbft: HCAbft.o
##	$(CC) $(CFLAGES) -o HCAbft HCAbft.o
##HCAbft.o: HCAbft.c
##	$(CC) $(CFLAGES) -c HCAbft.c
#
#
#HCAbft: HCAbft.o
#HCAbft.o: HCAbft.c
#
#%: %.o
#	$(CC) $(CFLIGES) $^ -lsimgrid -o $@
#%.o: %.c
#	$(CC) $(CFLAGE) -c -o $@ $<
#.PHONY:clean
#clean:
#	rm -rf *.o
